
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://raw.githubusercontent.com/swsnr/rust-supply-chain/refs/heads/main/audits.toml"

[policy.mdcat]
audit-as-crates-io = false
criteria = "safe-to-run"
notes = "mdcat is a command line tool and usally not exposed to fully untrusted input"

[policy.mdcat-http-reqwest]
audit-as-crates-io = false
criteria = "safe-to-run"
notes = "mdcat is a command line tool and usally not exposed to fully untrusted input"

[policy.pulldown-cmark-mdcat]
audit-as-crates-io = false
criteria = "safe-to-run"
notes = "mdcat is a command line tool and usally not exposed to fully untrusted input"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-run"

[[exemptions.aligned-vec]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-run"

[[exemptions.alloc-stdlib]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.arbitrary]]
version = "1.4.1"
criteria = "safe-to-run"

[[exemptions.arg_enum_proc_macro]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.arrayref]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.async-compression]]
version = "0.4.18"
criteria = "safe-to-run"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.av1-grain]]
version = "0.2.3"
criteria = "safe-to-run"

[[exemptions.avif-serialize]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-run"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-run"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-run"

[[exemptions.bitstream-io]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.brotli]]
version = "7.0.0"
criteria = "safe-to-run"

[[exemptions.brotli-decompressor]]
version = "4.0.1"
criteria = "safe-to-run"

[[exemptions.built]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.bytemuck]]
version = "1.20.0"
criteria = "safe-to-run"

[[exemptions.byteorder-lite]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.cfg-expr]]
version = "0.15.8"
criteria = "safe-to-run"

[[exemptions.clap_derive]]
version = "4.5.18"
criteria = "safe-to-run"

[[exemptions.console]]
version = "0.15.8"
criteria = "safe-to-run"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.crunchy]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.data-url]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.displaydoc]]
version = "0.2.5"
criteria = "safe-to-run"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.exr]]
version = "1.73.0"
criteria = "safe-to-run"

[[exemptions.fancy-regex]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.2.0"
criteria = "safe-to-run"

[[exemptions.fontconfig-parser]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.fontdb]]
version = "0.21.0"
criteria = "safe-to-run"

[[exemptions.gethostname]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.gif]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.1"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.http-body]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.human-panic]]
version = "2.0.2"
criteria = "safe-to-run"

[[exemptions.hyper-rustls]]
version = "0.27.3"
criteria = "safe-to-run"

[[exemptions.icu_properties]]
version = "1.5.1"
criteria = "safe-to-run"

[[exemptions.idna]]
version = "1.0.3"
criteria = "safe-to-run"

[[exemptions.idna_adapter]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.image]]
version = "0.25.5"
criteria = "safe-to-run"

[[exemptions.image-webp]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.imagesize]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.imgref]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.insta]]
version = "1.41.1"
criteria = "safe-to-run"

[[exemptions.interpolate_name]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.ipnet]]
version = "2.10.1"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.13"
criteria = "safe-to-run"

[[exemptions.jobserver]]
version = "0.1.32"
criteria = "safe-to-run"

[[exemptions.jpeg-decoder]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.kurbo]]
version = "0.11.1"
criteria = "safe-to-run"

[[exemptions.lebe]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.164"
criteria = "safe-to-run"

[[exemptions.libfuzzer-sys]]
version = "0.4.8"
criteria = "safe-to-run"

[[exemptions.libm]]
version = "0.2.11"
criteria = "safe-to-run"

[[exemptions.libz-sys]]
version = "1.1.20"
criteria = "safe-to-run"

[[exemptions.litemap]]
version = "0.7.4"
criteria = "safe-to-run"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-run"

[[exemptions.loop9]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.maybe-rayon]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.memmap2]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.mio]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.native-tls]]
version = "0.2.12"
criteria = "safe-to-run"

[[exemptions.new_debug_unreachable]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.noop_proc_macro]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.num-bigint]]
version = "0.4.6"
criteria = "safe-to-run"

[[exemptions.num-integer]]
version = "0.1.46"
criteria = "safe-to-run"

[[exemptions.num-rational]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.object]]
version = "0.36.5"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.20.1"
criteria = "safe-to-run"

[[exemptions.openssl]]
version = "0.10.68"
criteria = "safe-to-run"

[[exemptions.openssl-sys]]
version = "0.9.104"
criteria = "safe-to-run"

[[exemptions.os_info]]
version = "3.8.2"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.3"
criteria = "safe-to-run"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-run"

[[exemptions.pico-args]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.pkg-config]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.plist]]
version = "1.7.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.92"
criteria = "safe-to-run"

[[exemptions.profiling]]
version = "1.0.16"
criteria = "safe-to-run"

[[exemptions.profiling-procmacros]]
version = "1.0.16"
criteria = "safe-to-run"

[[exemptions.pulldown-cmark]]
version = "0.12.2"
criteria = "safe-to-run"

[[exemptions.pulldown-cmark-escape]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.qoi]]
version = "0.4.1"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "2.0.1"
criteria = "safe-to-run"

[[exemptions.quick-xml]]
version = "0.32.0"
criteria = "safe-to-run"

[[exemptions.rav1e]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.ravif]]
version = "0.11.11"
criteria = "safe-to-run"

[[exemptions.rayon]]
version = "1.10.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.12.1"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.resvg]]
version = "0.43.0"
criteria = "safe-to-run"

[[exemptions.rgb]]
version = "0.8.50"
criteria = "safe-to-run"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-run"

[[exemptions.roxmltree]]
version = "0.20.0"
criteria = "safe-to-run"

[[exemptions.rustls]]
version = "0.23.18"
criteria = "safe-to-run"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-run"

[[exemptions.rustls-pki-types]]
version = "1.10.0"
criteria = "safe-to-run"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-run"

[[exemptions.rustybuzz]]
version = "0.18.0"
criteria = "safe-to-run"

[[exemptions.schannel]]
version = "0.1.27"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-run"

[[exemptions.security-framework-sys]]
version = "2.12.1"
criteria = "safe-to-run"

[[exemptions.serde_spanned]]
version = "0.6.8"
criteria = "safe-to-run"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-run"

[[exemptions.simd_helpers]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.similar]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.similar-asserts]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.simplecss]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.slotmap]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-run"

[[exemptions.strict-num]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-run"

[[exemptions.svgtypes]]
version = "0.15.2"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.89"
criteria = "safe-to-run"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.syntect]]
version = "5.2.0"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "6.2.2"
criteria = "safe-to-run"

[[exemptions.target-lexicon]]
version = "0.12.16"
criteria = "safe-to-run"

[[exemptions.temp-env]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.tempfile]]
version = "3.14.0"
criteria = "safe-to-run"

[[exemptions.terminal_size]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.thread_local]]
version = "1.1.8"
criteria = "safe-to-run"

[[exemptions.tiff]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-run"

[[exemptions.tiny-skia]]
version = "0.11.4"
criteria = "safe-to-run"

[[exemptions.tiny-skia-path]]
version = "0.11.4"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.4.0"
criteria = "safe-to-run"

[[exemptions.tokio-rustls]]
version = "0.26.0"
criteria = "safe-to-run"

[[exemptions.tokio-stream]]
version = "0.1.16"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.22"
criteria = "safe-to-run"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-run"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-run"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-run"

[[exemptions.tracing-subscriber]]
version = "0.3.18"
criteria = "safe-to-run"

[[exemptions.ttf-parser]]
version = "0.24.1"
criteria = "safe-to-run"

[[exemptions.unicode-bidi]]
version = "0.3.17"
criteria = "safe-to-run"

[[exemptions.unicode-bidi-mirroring]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.unicode-ccc]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.14"
criteria = "safe-to-run"

[[exemptions.unicode-properties]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.unicode-script]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.unicode-segmentation]]
version = "1.12.0"
criteria = "safe-to-run"

[[exemptions.unicode-vo]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.url]]
version = "2.5.4"
criteria = "safe-to-run"

[[exemptions.usvg]]
version = "0.43.0"
criteria = "safe-to-run"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.uuid]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.v_frame]]
version = "0.3.8"
criteria = "safe-to-run"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.45"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.weezl]]
version = "0.1.8"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-registry]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.windows-result]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.windows-strings]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.6.20"
criteria = "safe-to-run"

[[exemptions.xmlwriter]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.yoke]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.yoke-derive]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-run"

[[exemptions.zerofrom]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.zerofrom-derive]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-run"

[[exemptions.zerovec-derive]]
version = "0.10.3"
criteria = "safe-to-run"

[[exemptions.zune-core]]
version = "0.4.12"
criteria = "safe-to-run"

[[exemptions.zune-inflate]]
version = "0.2.54"
criteria = "safe-to-run"

[[exemptions.zune-jpeg]]
version = "0.4.13"
criteria = "safe-to-run"
