[package]
name = "pulldown-cmark-mdcat"
description = "Render pulldown-cmark events to TTY"
readme = "README.md"
documentation = "https://docs.rs/pulldown-cmark"
keywords = ["markdown", "less", "cat", "cmark"]
homepage.workspace = true
repository.workspace = true
version.workspace = true
categories.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["svg", "regex-fancy", "image-processing"]
svg = ["dep:resvg"]
image-processing = ["dep:image"]
regex-fancy = ["syntect/regex-fancy"]
onig = ["syntect/regex-onig"]

[dependencies]
base64 = { version = "0.21.0", default-features = false, features = ["std"] }
anstyle = { version = "1.0.0", default-features = false }
gethostname = "0.4.2"
mime = { version = "0.3.17", default-features = false }
mime_guess = { version = "2.0.4", default-features = false }
once_cell = { version = "1.17.1", default-features = false }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ['simd'] }
syntect = { version = "5.0.0", default-features = false, features = ["parsing"] }
textwrap = { version = "0.16.0", default-features = false, features = ["unicode-linebreak", "unicode-width"] }
thiserror = { version = "1.0.40", default-features = false }
tracing = { version = "0.1.37", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "std", "fmt", "ansi"] }
url = "2.3.1"

# Optional for svg support
resvg = { version = "0.31.0", optional = true, default-features = false, features = ["text", "system-fonts", "memmap-fonts"] }
# Optional for image processing support; we deliberately build with default
# features to include all possible image formats
image = { version = "0.24.6", optional = true }

[dev-dependencies]
glob = "0.3.1"
similar-asserts = "1.4.2"
syntect = { version = "5.0.0", default-features = false, features = ["default-syntaxes"] }
temp-env = { version = "0.3.4", default-features = false }

# Our own development dependencies; we can just use a path dependency here.
mdcat-http-reqwest = { path = "../mdcat-http-reqwest/", features = ["rustls-tls-native-roots"] }

[build-dependencies]
syntect = { version = "5.0.0", default-features = false, features = ["plist-load", "dump-create"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.37.11", default-features = false, features = ['termios', 'std'] }

[target.'cfg(windows)'.dependencies]
terminal_size = "0.2.6"

[package.metadata.release]
release = true
