[package]
name = "pulldown-cmark-mdcat"
description = "Render pulldown-cmark events to TTY"
readme = "README.md"
documentation = "https://docs.rs/pulldown-cmark"
keywords = ["markdown", "less", "cat", "cmark"]
homepage.workspace = true
repository.workspace = true
version.workspace = true
categories.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { version = "1.0.70", default-features = false, features = ["std"] }
base64 = { version = "0.21.0", default-features = false }
anstyle = { version = "0.3.5", default-features = false }
gethostname = "0.4.1"
image = "0.24.6"
mime = { version = "0.3.17", default-features = false }
mime_guess = { version = "2.0.4", default-features = false }
once_cell = { version = "1.17.1", default-features = false }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ['simd'] }
resvg = { version = "0.31.0", default-features = false, features = ["text", "system-fonts", "memmap-fonts"] }
syntect = { version = "5.0.0", default-features = false, features = ["parsing"] }
textwrap = { version = "0.16.0", default-features = false, features = ["unicode-linebreak", "unicode-width"] }
tracing = { version = "0.1.37", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "std", "fmt", "ansi"] }
url = "2.3.1"

[dev-dependencies]
glob = "0.3.1"
pretty_assertions = "1.3.0"
syntect = { version = "5.0.0", default-features = false, features = ["regex-fancy", "default-syntaxes"] }
mdcat-http-reqwest = { version = "1.1.1", path = "../mdcat-http-reqwest/", features = ["rustls-tls-native-roots"] }

[build-dependencies]
syntect = { version = "5.0.0", default-features = false, features = ["plist-load", "dump-create"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.141"

[target.'cfg(windows)'.dependencies]
terminal_size = "0.2.6"

