name: "Test & Lint"

on:
  push:
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags_ignore: '*'
  pull_request:

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSL -o ./shfmt https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_amd64
          chmod 700 ./shfmt
      - run: ./shfmt -i 4 -l -d scripts/*
      - run: shellcheck -S style -o all scripts/*

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  manpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo gem install asciidoctor
      - run: asciidoctor -b manpage -a reproducible --warnings mdcat.1.adoc
      - run: man -l --warnings=w --pager=cat mdcat.1
        env:
          MANWIDTH: 80

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Check default build
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        # The action uses --all-features by default, but we'd only like to check default
        arguments: ""
    # Check the static build for lib musl
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        arguments: "--no-default-features --features static"

  # Test pulldown-cmark-mdcat
  test-pulldown-cmark-mdcat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Test name
        cargo_opts:
          - ''
          - '--no-default-features'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo build -p pulldown-cmark-mdcat --all-targets --locked ${{ matrix.cargo_opts }}
      - run: cargo clippy -p pulldown-cmark-mdcat --all-targets --locked ${{ matrix.cargo_opts }}
      - run: cargo test -p pulldown-cmark-mdcat --locked ${{ matrix.cargo_opts }}
      - run: cargo doc -p pulldown-cmark-mdcat --locked ${{ matrix.cargo_opts }}

  test-mdcat-http-reqwest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo build -p mdcat-http-reqwest --all-targets --locked ${{ matrix.cargo_opts }}
      - run: cargo clippy -p mdcat-http-reqwest --all-targets --locked ${{ matrix.cargo_opts }}
      - run: cargo test -p mdcat-http-reqwest --locked ${{ matrix.cargo_opts }}
      - run: cargo doc -p mdcat-http-reqwest --locked ${{ matrix.cargo_opts }}

  # Test mdcat itself
  test-mdcat:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          # Default linux build
          - x86_64-unknown-linux-gnu
          # Statically linked linux builds
          - x86_64-unknown-linux-musl
          # macOS
          - x86_64-apple-darwin
          # Windows
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cargo_opts: "--no-default-features --features static"
          - target: x86_64-apple-darwin
            os: macOS-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Install musl tools for musl target
      - run: sudo apt-get install musl-tools
        if: "contains(matrix.target, 'musl')"
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy
      # Build, including tests, to report build failures and measure build time separately from tests
      - run: cargo build --all-targets --locked --target ${{ matrix.target }} ${{ matrix.cargo_opts }}
      - run: cargo clippy --all-targets --locked --target ${{ matrix.target }} ${{ matrix.cargo_opts }}
      - run: cargo test --locked --target ${{ matrix.target }} ${{ matrix.cargo_opts }}
      - run: cargo doc --locked --target ${{ matrix.target }} ${{ matrix.cargo_opts }}
      - run: cargo run --target ${{ matrix.target }} ${{ matrix.cargo_opts }} -- sample/common-mark.md
